tinyMCE.addI18n({cn:{
common:{
edit_confirm:"您想在编辑区域上使用所见即所得编辑器么?",
apply:"Apply",
insert:"插入",
update:"更新",
cancel:"取消",
close:"关闭",
browse:"浏览",
class_name:"类型",
not_set:"-- Not set --",
clipboard_msg:"剪切/复制/粘贴功能在 Mozilla 和 Firefox 浏览器中不支持。您希望获得更多的信息吗?",
clipboard_no_support:"您的浏览器目前不支持，使用键盘快捷键来代替.",
popup_blocked:"对不起, 您的浏览器禁止了弹出式窗口。为了让您使用到最完善的功能，请对本网站的弹出式窗口解除禁止.",
invalid_data:"错误：输入无效值.",
more_colors:"更多颜色"
},
contextmenu:{
align:"对齐",
left:"居左",
center:"居中",
right:"居右",
full:"两端"
},
insertdatetime:{
date_fmt:"%Y-%m-%d",
time_fmt:"%H:%M:%S",
insertdate_desc:"插入日期",
inserttime_desc:"插入时间",
months_long:"January,February,March,April,May,June,July,August,September,October,November,December",
months_short:"Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec",
day_long:"Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday",
day_short:"Sun,Mon,Tue,Wed,Thu,Fri,Sat,Sun"
},
print:{
print_desc:"打印"
},
preview:{
preview_desc:"预览"
},
directionality:{
ltr_desc:"方向左到右",
rtl_desc:"方向从右到左"
},
layer:{
insertlayer_desc:"插入新层",
forward_desc:"Move forward",
backward_desc:"Move backward",
absolute_desc:"切换绝对定位",
content:"新层..."
},
save:{
save_desc:"保存",
cancel_desc:"取消所有更改"
},
nonbreaking:{
nonbreaking_desc:"插入非中断空格字符"
},
iespell:{
iespell_desc:"运行拼写检查",
download:"ieSpell未检出。你想现在安装?"
},
advhr:{
advhr_desc:"水平线"
},
emotions:{
emotions_desc:"Emotions"
},
searchreplace:{
search_desc:"查找",
replace_desc:"查找/替换"
},
advimage:{
image_desc:"插入/编辑图片"
},
advlink:{
link_desc:"插入/编辑链接"
},
xhtmlxtras:{
cite_desc:"引用",
abbr_desc:"Abbreviation",
acronym_desc:"首字母缩写",
del_desc:"删除",
ins_desc:"插入",
attribs_desc:"插入/编辑属性"
},
style:{
desc:"编辑CSS样式"
},
paste:{
paste_text_desc:"粘贴为纯文本",
paste_word_desc:"从Word中粘贴",
selectall_desc:"Select All"
},
paste_dlg:{
text_title:"使用键盘上的Ctrl + V粘贴到文本窗口.",
text_linebreaks:"保持换行符",
word_title:"Use CTRL+V on your keyboard to paste the text into the window."
},
table:{
desc:"插入表格",
row_before_desc:"插入行到首行",
row_after_desc:"插入行到末尾",
delete_row_desc:"删除行",
col_before_desc:"插入列到首列",
col_after_desc:"插入行到末列",
delete_col_desc:"删除列",
split_cells_desc:"拆分合并的表格单元格",
merge_cells_desc:"合并表格单元格",
row_desc:"行属性",
cell_desc:"元格属性",
props_desc:"表格属性",
paste_row_before_desc:"Paste table row before",
paste_row_after_desc:"Paste table row after",
cut_row_desc:"剪切行",
copy_row_desc:"复制行",
del:"删除表格",
row:"行",
col:"Column",
cell:"Cell"
},
autosave:{
unload_msg:"如果离开此页面导航，您所做的更改将丢失."
},
fullscreen:{
desc:"切换全屏模式"
},
media:{
desc:"Insert / edit embedded media",
edit:"Edit embedded media"
},
fullpage:{
desc:"文档属性"
},
template:{
desc:"插入预定义的模板内容"
},
visualchars:{
desc:"可视开/关控制字符."
},
spellchecker:{
desc:"切换拼写检查",
menu:"拼写检查设置",
ignore_word:"忽略单词",
ignore_words:"忽略所有",
langs:"语言",
wait:"请稍候...",
sug:"建议",
no_sug:"没有建议",
no_mpell:"没有发现拼写错误."
},
pagebreak:{
desc:"插入分页符."
}}});