tinyMCE.addI18n('cn.advimage_dlg',{
tab_general:"普通",
tab_appearance:"Appearance",
tab_advanced:"高级",
general:"普通",
title:"标题",
preview:"预览",
constrain_proportions:"Constrain proportions",
langdir:"Language direction",
langcode:"Language code",
long_desc:"Long description link",
style:"Style",
classes:"Classes",
ltr:"Left to right",
rtl:"Right to left",
id:"Id",
map:"Image map",
swap_image:"Swap image",
alt_image:"Alternative image",
mouseover:"for mouse over",
mouseout:"for mouse out",
misc:"Miscellaneous",
example_img:"Appearance preview image",
missing_alt:"Are you sure you want to continue without including an Image Description? Without it the image may not be accessible to some users with disabilities, or to those using a text browser, or browsing the Web with images turned off.",
dialog_title:"插入/编辑图像",
src:"图片地址",
alt:"图片说明",
list:"图片列表",
border:"边框",
dimensions:"尺寸",
vspace:"垂直间距",
hspace:"Horizontal space",
align:"对齐",
align_baseline:"底部",
align_top:"顶部",
align_middle:"中间",
align_bottom:"底部",
align_texttop:"文字上方",
align_textbottom:"文字下方",
align_left:"左对齐",
align_right:"右对齐",
image_list:"图片列表"
});