tinyMCE.addI18n('cn.advanced',{
style_select:"样式",
font_size:"字体大小",
fontdefault:"字体",
block:"格式",
paragraph:"Paragraph",
div:"Div",
address:"地址",
pre:"Preformatted",
h1:"Heading 1",
h2:"Heading 2",
h3:"Heading 3",
h4:"Heading 4",
h5:"Heading 5",
h6:"Heading 6",
blockquote:"Blockquote",
code:"代码",
samp:"代码示例",
dt:"Definition term ",
dd:"Definition description",
bold_desc:"粗体 (Ctrl+B)",
italic_desc:"斜体 (Ctrl+I)",
underline_desc:"下划线 (Ctrl+U)",
striketrough_desc:"Strikethrough",
justifyleft_desc:"左对齐",
justifycenter_desc:"居中对齐",
justifyright_desc:"右对齐",
justifyfull_desc:"两端对齐",
bullist_desc:"无序列表",
numlist_desc:"有序列表",
outdent_desc:"凸出",
indent_desc:"缩进",
undo_desc:"复原 (Ctrl+Z)",
redo_desc:"重做 (Ctrl+Y)",
link_desc:"插入/编辑链接",
unlink_desc:"取消链接",
image_desc:"插入/编辑图像",
cleanup_desc:"清理代码",
code_desc:"编辑HTML源",
sub_desc:"Subscript",
sup_desc:"Superscript",
hr_desc:"Insert horizontal ruler",
removeformat_desc:"Remove formatting",
custom1_desc:"Your custom description here",
forecolor_desc:"选择文字颜色",
backcolor_desc:"Select background color",
charmap_desc:"Insert custom character",
visualaid_desc:"Toggle guidelines/invisible elements",
anchor_desc:"插入/编辑锚点",
cut_desc:"剪切",
copy_desc:"复制",
paste_desc:"粘贴",
image_props_desc:"图像属性",
newdocument_desc:"New document",
help_desc:"帮助",
blockquote_desc:"Blockquote",
clipboard_msg:"Copy/Cut/Paste is not available in Mozilla and Firefox.\r\nDo you want more information about this issue?",
path:"Path",
newdocument:"Are you sure you want clear all contents?",
toolbar_focus:"Jump to tool buttons - Alt+Q, Jump to editor - Alt-Z, Jump to element path - Alt-X",
more_colors:"More colors"
});