tinyMCE.addI18n('cn.advanced_dlg',{
about_title:"关于 TinyMCE",
about_general:"关于",
about_help:"帮助",
about_license:"许可",
about_plugins:"插件",
about_plugin:"Plugin",
about_author:"Author",
about_version:"Version",
about_loaded:"Loaded plugins",
anchor_title:"插入/编辑锚点",
anchor_name:"Anchor name",
code_title:"HTML源代码编辑器",
code_wordwrap:"Word wrap",
colorpicker_title:"Select a color",
colorpicker_picker_tab:"Picker",
colorpicker_picker_title:"Color picker",
colorpicker_palette_tab:"Palette",
colorpicker_palette_title:"Palette colors",
colorpicker_named_tab:"Named",
colorpicker_named_title:"Named colors",
colorpicker_color:"Color:",
colorpicker_name:"Name:",
charmap_title:"Select custom character",
image_title:"插入/编辑图像",
image_src:"图片地址",
image_alt:"图片说明",
image_list:"图片列表",
image_border:"边框",
image_dimensions:"尺寸",
image_vspace:"垂直间距",
image_hspace:"水平间距",
image_align:"对齐",
image_align_baseline:"底部",
image_align_top:"顶部",
image_align_middle:"中间",
image_align_bottom:"底部",
image_align_texttop:"文字上方",
image_align_textbottom:"文字下方",
image_align_left:"左对齐",
image_align_right:"右对齐",
link_title:"编辑/插入链接",
link_url:"取消链接",
link_target:"Target",
link_target_same:"Open link in the same window",
link_target_blank:"Open link in a new window",
link_titlefield:"Title",
link_is_email:"The URL you entered seems to be an email address, do you want to add the required mailto: prefix?",
link_is_external:"The URL you entered seems to external link, do you want to add the required http:// prefix?",
link_list:"Link list"
});